# Generated by Django 3.2.7 on 2023-10-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('userid', models.EmailField(max_length=100)),
                ('status', models.BooleanField()),
                ('cdate', models.DateField()),
            ],
            options={
                'db_table': 'addtocart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(null='true')),
                ('created_at', models.CharField(max_length=255, null='true')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null='true')),
                ('Email', models.CharField(max_length=120, null='true')),
                ('Mobile', models.CharField(max_length=20, null='true')),
                ('Message', models.TextField(null='true')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteamname', models.CharField(max_length=150, null='true')),
                ('category', models.CharField(max_length=100, null='true')),
                ('price', models.CharField(max_length=100, null='true')),
                ('disprice', models.CharField(max_length=100, null='true')),
                ('description', models.TextField(null='true')),
                ('ppic', models.ImageField(default='', upload_to='static/products')),
                ('created_at', models.CharField(max_length=255, null='true')),
                ('updated_at', models.CharField(max_length=255, null='true')),
                ('seller_id', models.CharField(max_length=255, null='true')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ImageField(upload_to='')),
                ('userid', models.EmailField(max_length=100)),
                ('remarks', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
                ('odate', models.DateField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null='true')),
                ('email', models.CharField(max_length=255, null='true')),
                ('password', models.CharField(max_length=255, null='true')),
                ('cpassword', models.CharField(max_length=255, null='true')),
                ('address', models.CharField(max_length=255, null='true')),
                ('dob', models.CharField(max_length=255, null='true')),
                ('gender', models.CharField(max_length=255, null='true')),
                ('role', models.CharField(max_length=255, null='true')),
                ('contact', models.CharField(max_length=255, null='true')),
                ('ppic', models.ImageField(default='', upload_to='static/profile')),
                ('created_at', models.CharField(max_length=255, null='true')),
                ('updated_at', models.CharField(max_length=255, null='true')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
