# Generated by Django 3.2.7 on 2023-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_order_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null='true')),
                ('email', models.CharField(max_length=255, null='true')),
                ('password', models.CharField(max_length=255, null='true')),
                ('cpassword', models.CharField(max_length=255, null='true')),
                ('address', models.CharField(max_length=255, null='true')),
                ('dob', models.CharField(max_length=255, null='true')),
                ('gender', models.CharField(max_length=255, null='true')),
                ('role', models.CharField(max_length=255, null='true')),
                ('contact', models.CharField(max_length=255, null='true')),
                ('ppic', models.ImageField(default='', upload_to='static/profile')),
                ('created_at', models.CharField(max_length=255, null='true')),
                ('updated_at', models.CharField(max_length=255, null='true')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
